absoluteurl: //www.ici3d.org
subdomainurl: //www.ici3d.org/DAIDD
baseurl: /DAIDD
url: //www.ici3d.org
title: DAIDD 2026
longtitle: Clinic on Dynamical Approaches to Infectious Disease Data
summary: The fourteenth annual DAIDD clinic  ~  28 November - 05 December 2026
year: 2026
takingapps: true
applink: https://forms.gle/FE8ss43oiwPdhmdw8
markdown: kramdown
highlighter: rouge
includes_dir: ICI3D.github.io/_includes
layouts_dir: ICI3D.github.io/_layouts
data_dir: ICI3D.github.io/_data
collections:
  team:
    output: true
    permalink: /team/:name/
defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: profile
exclude:
  - README.md
  - run.sh
  - aims.sh
