absoluteurl: http://www.ici3d.org
subdomainurl: http://www.ici3d.org/DAIDD
baseurl: /DAIDD
url: http://www.ici3d.org
title: DAIDD 2022
longtitle: Clinic on Dynamical Approaches to Infectious Disease Data
summary: The eleventh annual DAIDD clinic  ~  December 11–17, 2022  ~  Virtual Edition
year: 2022
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-ici3d
collections:
  team:
    output: true
    permalink: /team/:name/
defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: profile
exclude:
  - README.md
  - run.sh
  - aims.sh
