absoluteurl: //www.ici3d.org
subdomainurl: //www.ici3d.org/DAIDD
baseurl: /DAIDD
url: //www.ici3d.org
title: DAIDD 2023
longtitle: Clinic on Dynamical Approaches to Infectious Disease Data
summary: The eleventh annual DAIDD clinic  ~  December 10–16, 2023  ~  Virtual Edition
year: 2023
markdown: kramdown
highlighter: rouge
includes_dir: ICI3D.github.io/_includes
layouts_dir: ICI3D.github.io/_layouts
data_dir: ICI3D.github.io/_data
collections:
  team:
    output: true
    permalink: /team/:name/
defaults:
  - scope:
      path: ""
      type: team
    values:
      layout: profile
exclude:
  - README.md
  - run.sh
  - aims.sh
